name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Docker CLI
        run: |
          echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Determine modified services
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt || echo "" > modified_files.txt
          modified_service=$(grep -oP '^.*?(?=/Dockerfile)' modified_files.txt | uniq)
          echo "::set-output name=services::${modified_service}"

      - name: Build and push Docker images
        run: |
          services=(${{ steps.changes.outputs.services }})
          for service in "${services[@]}"; do
            if [[ -f "${service}/Dockerfile" ]]; then
              docker build -t "${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}/${service}:${{ github.sha }}" -f "${service}/Dockerfile" .
              docker push "${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}/${service}:${{ github.sha }}"
            else
              docker push "${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}/${service}:${{ github.sha }}"
            fi
          done

      - name: Verify pushed images
        run: |
          docker images "${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}"
