name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine modified service
        id: git_diff
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified_files.txt
          echo "::set-output name=modified_service::$(grep -oP '^.*?(?=/docker-compose\.txt)' modified_files.txt | uniq)"

      - name: Build and Push Docker Image
        env:
          GITHUB_VERSION: ${{ github.ref }}
        run: |
          # Build and push Docker image for the modified service
          service_name=${{ steps.git_diff.outputs.modified_service }}
          if [[ -n "$service_name" ]]; then
            cd $service_name

            # Extract the service name from the current directory
            service_name=${service_name##*/}

            # Build the Docker image with the respective Dockerfile and tag it with the GitHub version
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$service_name:${GITHUB_VERSION} .

            # Push the Docker image to the Docker registry
            docker push ${{ secrets.DOCKER_USERNAME }}/$service_name:${GITHUB_VERSION}

            cd ..
          fi
