...
- name: Build and push app service image
  uses: docker/build-push-action@v2
  with:
    context: .
    file: ./Dockerfile
    push: true
    tags: shafibhaii/app-service:${{ steps.version.outputs.tag }}

- name: Build and push db service image
  uses: docker/build-push-action@v2
  with:
    context: .
    file: ./docker-compose.yml
    push: true
    tags: shafibhaii/db-service:${{ steps.version.outputs.tag }}
    target: db

- name: Build and push hasura service image
  uses: docker/build-push-action@v2
  with:
    context: .
    file: ./docker-compose.yml
    push: true
    tags: shafibhaii/hasura-service:${{ steps.version.outputs.tag }}
    target: hasura
...
