name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo rm /usr/local/bin/docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push db service
        run: |
          docker-compose build db
          docker tag <your-docker-compose-project>_db:latest shafibhaii/db-service:latest
          docker push shafibhaii/db-service:latest

      - name: Build and push hasura service
        run: |
          docker-compose build hasura
          docker tag <your-docker-compose-project>_hasura:latest shafibhaii/hasura-service:latest
          docker push shafibhaii/hasura-service:latest
